import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeBootstrap from "./ui/theme-bootstrap";

const chillRound = localFont({
  src: "../public/ChillRoundM.woff2",
  variable: "--font-chill-round",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${chillRound.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ThemeBootstrap />
        {children}
      </body>
    </html>
  );
}
